# Generated by Django 3.2.9 on 2021-12-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Vehicle identity')),
                ('name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'car'), ('BIKE', 'bike'), ('BYCYCLE', 'bycycle'), ('AUTO', 'auto'), ('TRUCK', 'truckr')], default='CAR', max_length=15)),
                ('price', models.CharField(max_length=100)),
                ('speed', models.CharField(max_length=100)),
                ('wait_time_charges', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Vehicle booking identity')),
                ('latitude_coord', models.CharField(max_length=20)),
                ('longitude_coord', models.CharField(max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicle.vehicle')),
            ],
        ),
    ]
