# Generated by Django 3.2.9 on 2021-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('CAR', 'car'), ('BIKE', 'bike'), ('BYCYCLE', 'bycycle'), ('AUTO', 'auto'), ('TRUCK', 'truck')], default='CAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='vehiclebooking',
            name='latitude_coord',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclebooking',
            name='longitude_coord',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
